### ISSUE TITLE
All commands should run from 'site' directory

### ISSUE THREAD

**Issue by morganrallen** [flatiron/blacksmith#31]
After `blacksmith init`,  `blacksmith` `preview and generate` are run from the root directory. But running `blacksmith post` is required to be run from root/pages. I feel it should be aware of where the site content directory so all the commands can be run the root.

**Comment by morganrallen** [comment]
And for what its worth, since other modules seem to have `./pages` hardcoded its single line change in `./lib/commands/post.js`

changing line 25 from
 `var folder = res.title.toLowerCase().replace(/\W+/g, '-');`
to
`var folder = 'pages/'+res.title.toLowerCase().replace(/\W+/g, '-');`

**Comment by jfhbrook** [comment]
The problem is that you don't always have a flat directory structure in pages. Your post may be buried under many subfolders:

```
./blog/coding/my-sweet-post.html
```

for example. This is basically why `post` isn't pages-aware. It's possible, but not as easy as one might hope and with the added need of specifying subdirectories for the command if necessary.

I'm certainly open to making `blacksmith post` more powerful, I'm just not sure how to do so nicely.

**Comment by morganrallen** [comment]
If that is the case, and things do get buried in subdirectories, how would `blacksmith generate` operate properly? It appears to be hardcoded to look for ./pages ./authors ./theme

This tells me generate should always be run from the site root, therefore post can too.

**Comment by jfhbrook** [comment]
`generate` can (and does) traverse ./pages, ./authors and ./theme recursively. `post`, on the other hand, refers to a single resource and not a collection (or collections), which is why it behaves differently.

Like I said before: I'm open to `post` working from the site root, I just don't know what a good api for it would look like.

**Comment by indexzero** [comment]
Commands for pre `1.0.0` have been deprecated after rewrite.
